<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Teams_model extends CI_Model
{

    public $table = 'teams';
    public $id = 'team_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }

    // datatables
    function json() {
        $this->datatables->select('team_id,team_description,team_name');
        $this->datatables->from('teams');
        //add this line for join
        //$this->datatables->join('table2', 'teams.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('teams/read/$1'),'Read')." | ".anchor(site_url('teams/update/$1'),'Update')." | ".anchor(site_url('teams/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'team_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('team_id', $q);
	$this->db->or_like('team_description', $q);
	$this->db->or_like('team_name', $q);
	$this->db->or_like('parent_team_id', $q);
        $this->db->or_like('team_leader_id', $q);

	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('team_id', $q);
	$this->db->or_like('team_description', $q);
	$this->db->or_like('team_name', $q);
	$this->db->or_like('parent_team_id', $q);
        $this->db->or_like('team_leader_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Teams_model.php */
/* Location: ./application/models/Teams_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-30 11:54:10 */
/* http://harviacode.com */