<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Goals extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Goals_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('goals/goals_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Goals_model->json();
    }

    public function read($id) 
    {
        $row = $this->Goals_model->get_by_id($id);
        if ($row) {
            $data = array(
		'goal_id' => $row->goal_id,
		'goal_description' => $row->goal_description,
	    );
            $this->load->view('goals/goals_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('goals'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('goals/create_action'),
	    'goal_id' => set_value('goal_id'),
	    'goal_description' => set_value('goal_description'),
	);
        $this->load->view('goals/goals_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'goal_description' => $this->input->post('goal_description',TRUE),
	    );

            $this->Goals_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('goals'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Goals_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('goals/update_action'),
		'goal_id' => set_value('goal_id', $row->goal_id),
		'goal_description' => set_value('goal_description', $row->goal_description),
	    );
            $this->load->view('goals/goals_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('goals'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('goal_id', TRUE));
        } else {
            $data = array(
		'goal_description' => $this->input->post('goal_description',TRUE),
	    );

            $this->Goals_model->update($this->input->post('goal_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('goals'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Goals_model->get_by_id($id);

        if ($row) {
            $this->Goals_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('goals'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('goals'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('goal_description', 'goal description', 'trim|required');

	$this->form_validation->set_rules('goal_id', 'goal_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Goals.php */
/* Location: ./application/controllers/Goals.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-30 11:54:09 */
/* http://harviacode.com */