<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Objectives extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Objectives_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('objectives/objectives_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Objectives_model->json();
    }

    public function read($id) 
    {
        $row = $this->Objectives_model->get_by_id($id);
        if ($row) {
            $data = array(
		'objective_id' => $row->objective_id,
		'objective_description' => $row->objective_description,
	    );
            $this->load->view('objectives/objectives_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('objectives'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('objectives/create_action'),
	    'objective_id' => set_value('objective_id'),
	    'objective_description' => set_value('objective_description'),
	);
        $this->load->view('objectives/objectives_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'objective_description' => $this->input->post('objective_description',TRUE),
	    );

            $this->Objectives_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('objectives'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Objectives_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('objectives/update_action'),
		'objective_id' => set_value('objective_id', $row->objective_id),
		'objective_description' => set_value('objective_description', $row->objective_description),
	    );
            $this->load->view('objectives/objectives_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('objectives'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('objective_id', TRUE));
        } else {
            $data = array(
		'objective_description' => $this->input->post('objective_description',TRUE),
	    );

            $this->Objectives_model->update($this->input->post('objective_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('objectives'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Objectives_model->get_by_id($id);

        if ($row) {
            $this->Objectives_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('objectives'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('objectives'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('objective_description', 'objective description', 'trim|required');

	$this->form_validation->set_rules('objective_id', 'objective_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Objectives.php */
/* Location: ./application/controllers/Objectives.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-30 11:54:10 */
/* http://harviacode.com */