<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Teams_users extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Teams_users_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('teams_users/teams_users_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Teams_users_model->json();
    }

    public function read($id) 
    {
        $row = $this->Teams_users_model->get_by_id($id);
        if ($row) {
            $data = array(
		'team_id' => $row->team_id,
		'user_id' => $row->user_id,
		'id' => $row->id,
	    );
            $this->load->view('teams_users/teams_users_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('teams_users'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('teams_users/create_action'),
	    'team_id' => set_value('team_id'),
	    'user_id' => set_value('user_id'),
	    'id' => set_value('id'),
	);
        $this->load->view('teams_users/teams_users_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'team_id' => $this->input->post('team_id',TRUE),
		'user_id' => $this->input->post('user_id',TRUE),
	    );

            $this->Teams_users_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('teams_users'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Teams_users_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('teams_users/update_action'),
		'team_id' => set_value('team_id', $row->team_id),
		'user_id' => set_value('user_id', $row->user_id),
		'id' => set_value('id', $row->id),
	    );
            $this->load->view('teams_users/teams_users_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('teams_users'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'team_id' => $this->input->post('team_id',TRUE),
		'user_id' => $this->input->post('user_id',TRUE),
	    );

            $this->Teams_users_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('teams_users'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Teams_users_model->get_by_id($id);

        if ($row) {
            $this->Teams_users_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('teams_users'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('teams_users'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('team_id', 'team id', 'trim|required');
	$this->form_validation->set_rules('user_id', 'user id', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Teams_users.php */
/* Location: ./application/controllers/Teams_users.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-30 11:54:10 */
/* http://harviacode.com */