<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Teams extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Teams_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('teams/teams_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Teams_model->json();
    }

    public function read($id) 
    {
        $row = $this->Teams_model->get_by_id($id);
        if ($row) {
            $data = array(
		'team_id' => $row->team_id,
		'team_description' => $row->team_description,
		'team_name' => $row->team_name,
	    );
            $this->load->view('teams/teams_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('teams'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('teams/create_action'),
	    'team_id' => set_value('team_id'),
	    'team_description' => set_value('team_description'),
	    'team_name' => set_value('team_name'),
	);
        $this->load->view('teams/teams_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'team_description' => $this->input->post('team_description',TRUE),
		'team_name' => $this->input->post('team_name',TRUE),
	    );

            $this->Teams_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('teams'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Teams_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('teams/update_action'),
		'team_id' => set_value('team_id', $row->team_id),
		'team_description' => set_value('team_description', $row->team_description),
		'team_name' => set_value('team_name', $row->team_name),
	    );
            $this->load->view('teams/teams_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('teams'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('team_id', TRUE));
        } else {
            $data = array(
		'team_description' => $this->input->post('team_description',TRUE),
		'team_name' => $this->input->post('team_name',TRUE),
	    );

            $this->Teams_model->update($this->input->post('team_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('teams'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Teams_model->get_by_id($id);

        if ($row) {
            $this->Teams_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('teams'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('teams'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('team_description', 'team description', 'trim|required');
	$this->form_validation->set_rules('team_name', 'team name', 'trim|required');

	$this->form_validation->set_rules('team_id', 'team_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Teams.php */
/* Location: ./application/controllers/Teams.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-30 11:54:10 */
/* http://harviacode.com */